development:
  sessions:
    default:
      database: tapir_dev
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: tapir_prod
      hosts:
        - localhost:27017